language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - node
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run deploy-docs"
